# Generated by Django 4.2.14 on 2024-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='NB_GSM',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='NB_GSM',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='prenom',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
