# Generated by Django 4.2.14 on 2024-07-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_client_password_supervisor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='phone',
            new_name='NB_GSM',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='email',
            new_name='e_mail',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='lastName',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
