# Generated by Django 4.2.14 on 2024-07-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_phone_supervisor_nb_gsm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='nom',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='NB_GSM',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='prenom',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
