# Generated by Django 4.2.14 on 2024-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
