# Generated by Django 4.2.14 on 2024-07-21 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myProject',
            fields=[
                ('nomp', models.CharField(max_length=50, null=True)),
                ('geomp', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('descp', models.TextField(null=True)),
                ('debutp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('finp', models.DateTimeField(null=True)),
                ('cityp', models.CharField(max_length=255, null=True)),
                ('piece_joinde', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('locationp', location_field.models.plain.PlainLocationField(max_length=63, null=True)),
                ('polygon_id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('clientp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.client')),
                ('supervisorp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namep', models.CharField(blank=True, max_length=50, null=True)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to='managePJ.myproject')),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('Idnode', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('node_range', models.BigIntegerField(blank=True, null=True)),
                ('Sensors', models.CharField(max_length=50, null=True)),
                ('RSSI', models.BigIntegerField(null=True)),
                ('Battery_value', models.BigIntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('FWI', models.FloatField(default=0, null=True)),
                ('parc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='managePJ.parcelle')),
                ('polyg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='managePJ.myproject')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('IdData', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField(null=True)),
                ('humidity', models.BigIntegerField(null=True)),
                ('wind', models.FloatField(default=0, null=True)),
                ('rain', models.FloatField(default=0, null=True)),
                ('Data_date', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='managePJ.node')),
            ],
        ),
    ]
